DEFAULTSESSION=mate-session
exec mate-session





# set wallpaper
#bash /home/damien/.fehbg &

# run .Xresources
#xrdb -load ~/.Xresources

# set cursor look
#xsetroot -cursor_name left_ptr &

# night time colour temperature
#redshift &

# compositor
#compton --config ~/.config/compton.conf -b &

# mount windows partition
#mount /dev/sda4 /media/damien/Windows &

#set window manager
#exec xmonad

#start wired network connection
##sh /home/damien/.network_startup.sh
